In [1]:
A = rand(1:4, 3, 3)

3×3 Matrix{Int64}:
 4  4  4
 3  1  4
 1  1  4

In [2]:
B = A
C = copy(A)
[B C]

3×6 Matrix{Int64}:
 4  4  4  4  4  4
 3  1  4  3  1  4
 1  1  4  1  1  4

In [3]:
A[1] = 17
[B C]

3×6 Matrix{Int64}:
 17  4  4  4  4  4
  3  1  4  3  1  4
  1  1  4  1  1  4

In [4]:
x = ones(3)

3-element Vector{Float64}:
 1.0
 1.0
 1.0

In [5]:
b = A*x

3-element Vector{Float64}:
 25.0
  8.0
  6.0

In [6]:
Asym = A + A'

3×3 Matrix{Int64}:
 34  7  5
  7  2  5
  5  5  8

In [8]:
Apd = A'A

3×3 Matrix{Int64}:
 299  72  84
  72  18  24
  84  24  48

In [10]:
# solving a linear system
A\b

3-element Vector{Float64}:
 1.0000000000000004
 0.9999999999999978
 1.0000000000000004

In [11]:
Atall = A[:,1:2]
display(Atall)

3×2 Matrix{Int64}:
 17  4
  3  1
  1  1

In [12]:
Atall\b

2-element Vector{Float64}:
 -0.09090909090909136
  6.696969696969698

In [13]:
A = randn(3,3)

3×3 Matrix{Float64}:
  1.34591  2.26279    0.391125
  1.20814  0.840298   1.0229
 -1.39231  2.31192   -1.06771

In [14]:
[A[:,1] A[:,1]]\b

2-element Vector{Float64}:
 3.355247848136343
 3.355247848136343

In [15]:
Ashort = A[1:2,:]
display(Ashort)

2×3 Matrix{Float64}:
 1.34591  2.26279   0.391125
 1.20814  0.840298  1.0229

In [16]:
Ashort\b[1:2]

3-element Vector{Float64}:
  2.133166825703677
 10.329912888449673
 -3.1844358674197806